on:
  push:
    branches:
    - main
  
  release:
    types: [created]


name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy-test
    runs-on: ubuntu-latest
    environment: test
    
    steps:

    - name: Show Working directory
      run: pwd  

    - name: Show Working directory
      run: ls -la  

    - name: Checkout
      uses: actions/checkout@v2

    - name: Show Working directory
      run: ls -ltr  
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push flowise-test image to Amazon ECR
      id: build-flowise-test-id
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ypoint-images
        IMAGE_TAG: flowise-test
      run: |
        ls -ltr
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"